---
title: "Chr03_58Interval.Rmd"
author: "Louie Alexander"
date: '2022-08-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}

if (!require(readxl)) {
  install.packages("readxl")
}
if (!require(tidyverse)) {
  install.packages("tidyverse")
}
if (!require(reshape2)) {
  install.packages("reshape2")
}

library(readxl)
library(tidyverse)
library(reshape2)

```

```{r}
#This is the ".vcf" file for Duplications that documents which strains a given duplication occurs in
duplications <- read.table("final_conserved_adj.vcf",header=TRUE,sep = '\t')
```

```{r}
chromosome <- duplications %>% filter(CHROM == "Chr03") %>% dplyr::select( -c(ID, FORMAT, REF, ALT, QUAL, FILTER, INFO))

#This splits the chromosome into "steps" of 1M bp in size
chromosome$interval <- floor(chromosome$POS/10000)
chromosome <- chromosome %>% filter(POS >= 58000000 & POS <= 59000000) %>% select(-c(CHROM, POS))
```

```{r}
CA_filtered <- chromosome  %>% filter(CA != '0/0')
pi655_filtered <- chromosome %>% filter(pi655972 != '0/0')
pi510_filtered <- chromosome %>% filter(pi510757 != '0/0')
pi506_filtered <- chromosome %>% filter(pi506069 != '0/0')
pi329_filtered <- chromosome %>% filter(pi329311 != '0/0')     
leoti_filtered <- chromosome %>% filter(leoti != '0/0')        
pi229_filtered <- chromosome %>% filter(pi229841 != '0/0')
pi297_filtered <- chromosome %>% filter(pi297155 != '0/0')    
rio_filtered <- chromosome  %>% filter(rio != '0/0')   
```

```{r}
#This counts the numbers of features per 1M bp
CA = CA_filtered %>% count(interval) %>% rename(CA = n)
pi655 = pi655_filtered %>% count(interval) %>% rename(pi655972 = n)
pi510 = pi510_filtered %>% count(interval) %>% rename(pi510757 = n)
pi506 = pi506_filtered %>%  count(interval) %>% rename(pi506069 = n)
pi329 = pi329_filtered %>%  count(interval) %>% rename(pi329311 = n)
leoti = leoti_filtered %>%  count(interval) %>% rename(leoti = n)
pi229 = pi229_filtered %>%  count(interval) %>% rename(pi229841 = n)
pi297 = pi297_filtered %>%  count(interval) %>% rename(pi297155 = n)
rio = rio_filtered %>% count(interval) %>% rename(rio = n)
```

```{r}
merges <- full_join(CA, pi655)
merges <- full_join(merges, pi510)
merges <- full_join(pi506, merges)
merges <- full_join(pi329, merges)
merges <- full_join(leoti, merges)
merges <- full_join(pi229, merges)
merges <- full_join(pi297, merges)
merges <- full_join(rio, merges)

```

#new DF
```{r}
merges$interval <- as.numeric(merges$interval)
interval = seq(5800, 5900, 1)

for (inv in interval){
  if (!(inv %in% merges$interval)){
    merges[nrow(merges) + 1, "interval"] = as.numeric(inv)
  }
}

merges <- merges %>% mutate(sweetAVG = 0, cellulosicAVG = 0, 
                            rio = ifelse(is.na(rio), 0, rio), pi297155 = ifelse(is.na(pi297155), 0, pi297155), pi229841 = ifelse(is.na(pi229841), 0, pi229841), leoti = ifelse(is.na(leoti), 0, leoti), pi329311 = ifelse(is.na(pi329311), 0, pi329311), pi506069 = ifelse(is.na(pi506069), 0, pi506069), 
                            pi510757 = ifelse(is.na(pi510757), 0, pi510757), pi655972 = ifelse(is.na(pi655972), 0, pi655972), CA = ifelse(is.na(CA), 0, CA)) 

```


```{r}
#order the dataframe by interval
avg_Distance <- merges[order(merges$interval),]

avg_Distance$rio <- as.numeric(avg_Distance$rio)
avg_Distance$pi297155 <- as.numeric(avg_Distance$pi297155)
avg_Distance$pi229841 <- as.numeric(avg_Distance$pi229841)
avg_Distance$leoti <- as.numeric(avg_Distance$leoti)
avg_Distance$pi329311 <- as.numeric(avg_Distance$pi329311)
avg_Distance$pi506069 <- as.numeric(avg_Distance$pi506069)
avg_Distance$CA <- as.numeric(avg_Distance$CA)
avg_Distance$pi655972 <- as.numeric(avg_Distance$pi655972)
avg_Distance$pi510757 <- as.numeric(avg_Distance$pi510757)


#Go through each row to find means for sweet and cellulosic
for (row in 1:nrow(avg_Distance)) {
  #add avg for Sweet sorghum
  avg_Distance[row,"sweetAVG"] = round((avg_Distance[row,"rio"] + avg_Distance[row,"CA"] + avg_Distance[row,"leoti"])/3, 2)
  #add avg for Biomass sorghum
  avg_Distance[row,"cellulosicAVG"] = round((avg_Distance[row,"pi655972"] + avg_Distance[row,"pi510757"] + avg_Distance[row,"pi506069"] + avg_Distance[row,"pi329311"] + avg_Distance[row,"pi229841"] + avg_Distance[row,"pi297155"])/6, 2) 
} 

avg_Distance <- avg_Distance %>% dplyr::select(interval, sweetAVG, cellulosicAVG)
```


```{r}
data_long <- melt(avg_Distance, id = "interval")
data_long <- data_long %>% mutate(value = ifelse(variable == "cellulosicAVG", value * -1, value))

sweet <- data_long %>% filter(variable == "sweetAVG")
cell <- data_long %>% filter(variable == "cellulosicAVG")
splineSw <- as.data.frame(spline(sweet$interval, sweet$value))
splineCe <- as.data.frame(spline(cell$interval, cell$value))    

```

##BEST PLOT
```{r}

ggplot(data = data_long) + 
  geom_line(data=splineSw, aes(x=x, y=y), color = "#E69F00") + 
  geom_line(data=splineCe, aes(x=x, y=y), color= "#009E73") + 
  geom_area(data=splineSw, aes(x=x, y=y), fill = "#E69F00") + 
  geom_area(data=splineCe, aes(x=x, y=y), fill = "#009E73") +
  annotate("rect", xmin = 5893, xmax = 5897, ymin = -1.0, ymax = 1.0, alpha = .25,fill = "#921414") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  ggtitle("Chromosome 3 Interval 58 Frequency of Duplications") + 
  xlab("Interval (10,000 bp)") + 
  ylab("Number of Features")
```
